{% set name = "pyodide-py" %}
{% set version = "0.23.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyodide-py-{{ version }}.tar.gz
  sha256: 62848c0838e1173eb7e86daa94e5772dd2c25bdd6bd31dc2fa4d089fa89872b1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10

test:
  imports:
    - pyodide
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyodide/pyodide
  summary: '"A Python package providing core interpreter functionality for Pyodide."'
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yuvipanda
